# /*
#  * This file is autogenerated by: generate_densities.py 
#  * 
#  * NOTE: Any modifications made in this file will be lost next time 
#  *       generate_densities.py is run.
#  */

set(CHEMCACHE_DENSITY_SOURCE
    defaults/atomic_densities/3-21G.cpp
    defaults/atomic_densities/6-31G.cpp
    defaults/atomic_densities/STO-3G.cpp
    defaults/atomic_densities/aug-cc-pVTZ.cpp
)