/*
 * Copyright 2022 NWChemEx-Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is autogenerated by: generate_densities.py 
 * 
 * NOTE: Any modifications made in this file will be lost next time 
 *       generate_densities.py is run.
 */

#pragma once
#include <pluginplay/pluginplay.hpp>

namespace chemcache {

// Module declarations will go here
DECLARE_MODULE(three_dash_21g_atom_dm);
DECLARE_MODULE(six_dash_31g_atom_dm);
DECLARE_MODULE(six_dash_31g_st__atom_dm);
DECLARE_MODULE(aug_dash_cc_dash_pvtz_atom_dm);
DECLARE_MODULE(mini_atom_dm);
DECLARE_MODULE(sto_dash_3g_atom_dm);

namespace atom_dm_mods {

inline void set_defaults(pluginplay::ModuleManager& mm) {
    // Default submodules within this subcollection will be set here
    mm.change_submod("3-21g atomic dm", "AO Basis", "3-21g atomic basis");
    mm.change_submod("6-31g atomic dm", "AO Basis", "6-31g atomic basis");
    mm.change_submod("6-31g_st_ atomic dm", "AO Basis", "6-31g_st_ atomic basis");
    mm.change_submod("aug-cc-pvtz atomic dm", "AO Basis", "aug-cc-pvtz atomic basis");
    mm.change_submod("mini atomic dm", "AO Basis", "mini atomic basis");
    mm.change_submod("sto-3g atomic dm", "AO Basis", "sto-3g atomic basis");
}

inline void load_modules(pluginplay::ModuleManager& mm) {
    // Modules will be added to the ModuleManager here
    mm.add_module<three_dash_21g_atom_dm>("3-21g atomic dm");
    mm.add_module<six_dash_31g_atom_dm>("6-31g atomic dm");
    mm.add_module<six_dash_31g_st__atom_dm>("6-31g_st_ atomic dm");
    mm.add_module<aug_dash_cc_dash_pvtz_atom_dm>("aug-cc-pvtz atomic dm");
    mm.add_module<mini_atom_dm>("mini atomic dm");
    mm.add_module<sto_dash_3g_atom_dm>("sto-3g atomic dm");

    set_defaults(mm);
}

} // namespace atom_dm_mods

} // namespace chemcache
