/*
 * Copyright 2025 NWChemEx-Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is autogenerated by: generate_basis.py
 *
 * NOTE: Any modifications made in this file will be lost next time
 *       generate_basis.py is run.
 */

#include "cc_dash_pv_oparen_5_plus_d_cparen_z.hpp"
#include <simde/basis_set/atomic_basis_set.hpp>
#include <simde/types.hpp>

namespace chemcache {

using abs_t     = simde::type::atomic_basis_set;
using shell_t   = simde::type::shell;
using center_t  = simde::type::point;
using shells_t  = std::vector<shell_t>;
using doubles_t = std::vector<double>;
using pure_t    = chemist::ShellType;

abs_t cc_dash_pv_oparen_5_plus_d_cparen_z_13() {
    // Basis Set name and origin point
    std::string name("cc-pv(5+d)z");
    center_t r0(0.0, 0.0, 0.0);

    auto make_shell = [&r0](auto pure, auto l, const doubles_t& cs,
                            const doubles_t& es) {
        return shell_t(pure, l, cs.begin(), cs.end(), es.begin(), es.end(), r0);
    };

    shells_t shells;
    shells.emplace_back(make_shell(
      pure_t::pure, 0,
      doubles_t{2.1396200000e-06,  1.6626400000e-05,  8.7516800000e-05,
                3.6899000000e-04,  1.3390300000e-03,  4.3563600000e-03,
                1.2895500000e-02,  3.4820100000e-02,  8.4353000000e-02,
                1.7590700000e-01,  2.9209100000e-01,  3.2822000000e-01,
                1.8692700000e-01,  3.1043000000e-02,  -5.0892200000e-04,
                1.4883600000e-03,  -2.7824100000e-04, 1.1875200000e-04,
                -6.6150000000e-05, 1.7595400000e-05},
      doubles_t{3.2690000000e+06, 4.8940000000e+05, 1.1140000000e+05,
                3.1560000000e+04, 1.0320000000e+04, 3.7310000000e+03,
                1.4560000000e+03, 6.0410000000e+02, 2.6350000000e+02,
                1.1980000000e+02, 5.6320000000e+01, 2.7190000000e+01,
                1.3260000000e+01, 6.0520000000e+00, 2.9810000000e+00,
                1.4760000000e+00, 7.3340000000e-01, 2.4470000000e-01,
                1.0880000000e-01, 4.6720000000e-02}));
    shells.emplace_back(make_shell(
      pure_t::pure, 0,
      doubles_t{-5.5602600000e-07, -4.3230300000e-06, -2.2741300000e-05,
                -9.6011600000e-05, -3.4837600000e-04, -1.1383600000e-03,
                -3.3874400000e-03, -9.3150500000e-03, -2.3302300000e-02,
                -5.2348600000e-02, -9.9949900000e-02, -1.5056000000e-01,
                -1.1912100000e-01, 1.0809100000e-01,  4.1112900000e-01,
                4.5721400000e-01,  1.7593800000e-01,  7.7061000000e-03,
                -1.6616800000e-03, 4.4534700000e-04},
      doubles_t{3.2690000000e+06, 4.8940000000e+05, 1.1140000000e+05,
                3.1560000000e+04, 1.0320000000e+04, 3.7310000000e+03,
                1.4560000000e+03, 6.0410000000e+02, 2.6350000000e+02,
                1.1980000000e+02, 5.6320000000e+01, 2.7190000000e+01,
                1.3260000000e+01, 6.0520000000e+00, 2.9810000000e+00,
                1.4760000000e+00, 7.3340000000e-01, 2.4470000000e-01,
                1.0880000000e-01, 4.6720000000e-02}));
    shells.emplace_back(make_shell(pure_t::pure, 0, doubles_t{1.0000000000e+00},
                                   doubles_t{7.3340000000e-01}));
    shells.emplace_back(make_shell(pure_t::pure, 0, doubles_t{1.0000000000e+00},
                                   doubles_t{2.4470000000e-01}));
    shells.emplace_back(make_shell(pure_t::pure, 0, doubles_t{1.0000000000e+00},
                                   doubles_t{1.0880000000e-01}));
    shells.emplace_back(make_shell(
      pure_t::pure, 0,
      doubles_t{1.2842300000e-07,  9.9751400000e-07,  5.2548000000e-06,
                2.2145000000e-05,  8.0546400000e-05,  2.6250600000e-04,
                7.8422000000e-04,  2.1503900000e-03,  5.4197400000e-03,
                1.2168600000e-02,  2.3682300000e-02,  3.6093700000e-02,
                3.0328400000e-02,  -3.0903400000e-02, -1.1912600000e-01,
                -2.1114500000e-01, -1.5794400000e-01, 3.3903800000e-01,
                6.1309700000e-01,  2.3516800000e-01},
      doubles_t{3.2690000000e+06, 4.8940000000e+05, 1.1140000000e+05,
                3.1560000000e+04, 1.0320000000e+04, 3.7310000000e+03,
                1.4560000000e+03, 6.0410000000e+02, 2.6350000000e+02,
                1.1980000000e+02, 5.6320000000e+01, 2.7190000000e+01,
                1.3260000000e+01, 6.0520000000e+00, 2.9810000000e+00,
                1.4760000000e+00, 7.3340000000e-01, 2.4470000000e-01,
                1.0880000000e-01, 4.6720000000e-02}));
    shells.emplace_back(make_shell(pure_t::pure, 0, doubles_t{1.0000000000e+00},
                                   doubles_t{4.6720000000e-02}));
    shells.emplace_back(make_shell(
      pure_t::pure, 1,
      doubles_t{2.0861300000e-04, 1.8100500000e-03, 9.7343300000e-03,
                3.7826600000e-02, 1.1089800000e-01, 2.3429500000e-01,
                3.4524500000e-01, 3.3143000000e-01, 1.4706400000e-01,
                1.2141100000e-02, -8.7163900000e-04, 4.3795700000e-04},
      doubles_t{1.4610000000e+03, 3.4620000000e+02, 1.1220000000e+02,
                4.2510000000e+01, 1.7720000000e+01, 7.8520000000e+00,
                3.5710000000e+00, 1.6370000000e+00, 7.3820000000e-01,
                2.5770000000e-01, 9.7730000000e-02, 3.6900000000e-02}));
    shells.emplace_back(make_shell(pure_t::pure, 1, doubles_t{1.0000000000e+00},
                                   doubles_t{7.3820000000e-01}));
    shells.emplace_back(make_shell(pure_t::pure, 1, doubles_t{1.0000000000e+00},
                                   doubles_t{2.5770000000e-01}));
    shells.emplace_back(make_shell(pure_t::pure, 1, doubles_t{1.0000000000e+00},
                                   doubles_t{9.7730000000e-02}));
    shells.emplace_back(make_shell(
      pure_t::pure, 1,
      doubles_t{-3.7194700000e-05, -3.2856300000e-04, -1.7426400000e-03,
                -6.9482800000e-03, -2.0280700000e-02, -4.4865700000e-02,
                -6.4327800000e-02, -7.5266600000e-02, 6.1600800000e-04,
                2.8781900000e-01, 5.4303000000e-01, 3.0186500000e-01},
      doubles_t{1.4610000000e+03, 3.4620000000e+02, 1.1220000000e+02,
                4.2510000000e+01, 1.7720000000e+01, 7.8520000000e+00,
                3.5710000000e+00, 1.6370000000e+00, 7.3820000000e-01,
                2.5770000000e-01, 9.7730000000e-02, 3.6900000000e-02}));
    shells.emplace_back(make_shell(pure_t::pure, 1, doubles_t{1.0000000000e+00},
                                   doubles_t{3.6900000000e-02}));
    shells.emplace_back(make_shell(pure_t::pure, 2, doubles_t{1.0000000000e+00},
                                   doubles_t{2.6390000000e+00}));
    shells.emplace_back(make_shell(pure_t::pure, 2, doubles_t{1.0000000000e+00},
                                   doubles_t{5.8800000000e-01}));
    shells.emplace_back(make_shell(pure_t::pure, 2, doubles_t{1.0000000000e+00},
                                   doubles_t{3.8000000000e-01}));
    shells.emplace_back(make_shell(pure_t::pure, 2, doubles_t{1.0000000000e+00},
                                   doubles_t{1.8000000000e-01}));
    shells.emplace_back(make_shell(pure_t::pure, 2, doubles_t{1.0000000000e+00},
                                   doubles_t{7.2800000000e-02}));
    shells.emplace_back(make_shell(pure_t::pure, 3, doubles_t{1.0000000000e+00},
                                   doubles_t{5.1300000000e-01}));
    shells.emplace_back(make_shell(pure_t::pure, 3, doubles_t{1.0000000000e+00},
                                   doubles_t{2.5800000000e-01}));
    shells.emplace_back(make_shell(pure_t::pure, 3, doubles_t{1.0000000000e+00},
                                   doubles_t{1.3000000000e-01}));
    shells.emplace_back(make_shell(pure_t::pure, 4, doubles_t{1.0000000000e+00},
                                   doubles_t{5.4300000000e-01}));
    shells.emplace_back(make_shell(pure_t::pure, 4, doubles_t{1.0000000000e+00},
                                   doubles_t{2.5200000000e-01}));
    shells.emplace_back(make_shell(pure_t::pure, 5, doubles_t{1.0000000000e+00},
                                   doubles_t{4.4600000000e-01}));
    return abs_t(name, 13, r0, shells.begin(), shells.end());
} // cc_dash_pv_oparen_5_plus_d_cparen_z_13

} // namespace chemcache
