/*
 * Copyright 2022 NWChemEx-Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is autogenerated by: generate_atomicinfo.py
 *
 * NOTE: Any modifications made in this file will be lost next time
 *       generate_atomicinfo.py is run.
 */

#include "atoms.hpp"
#include <simde/chemical_system/Z_from_symbol.hpp>
#include <simde/types.hpp>

namespace chemcache {

using z_pt = simde::ZFromSymbol;
using z_t  = simde::type::atomic_number;

static constexpr auto module_desc = R"(
Atomic Number from Atomic Symbol
---------------------------------

This module returns atomic number associated with the atomic symbol.
This module was autogenerated.
)";

MODULE_CTOR(Z_from_sym) { satisfies_property_type<z_pt>(); }

MODULE_RUN(Z_from_sym) {
    const auto& [sym] = z_pt::unwrap_inputs(inputs);

    z_t Z;
    if(sym == "H") {
        Z = 1;
    } else if(sym == "O") {
        Z = 8;
    } else {
        throw std::out_of_range("Z not available for Symbol");
    }

    auto rv = results();
    return z_pt::wrap_results(rv, Z);
}

} // namespace chemcache