/*
 * Copyright 2023 NWChemEx-Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Unlike other property loading funciton, this file is NOT generated by some python code.
 * This is due to the fact that in any case there is no need to load the atomic density
 * matrices for all elements and all basis sets. Y. Z. 02/24/23
 */

#include "chemcache/chemcache.hpp"
#include <chemist/chemist.hpp>
#include "nwx_atomic_densities.hpp"

namespace chemcache {

    void load_atom_dm(chemist::PeriodicTable::size_type Z, std::string basis_name, chemist::PeriodicTable& pt) {
        pt.add_atom_dm(Z, basis_name, chemcache::detail_::get_atomic_density_(basis_name, Z));

    } // function load_atom_dm

} // namespace chemcache