/*
 * Copyright 2022 NWChemEx-Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is autogenerated by: generate_basis.py
 *
 * NOTE: Any modifications made in this file will be lost next time
 *       generate_basis.py is run.
 */

#include "cc_dash_pcvtz.hpp"
#include <simde/basis_set/atomic_basis_set.hpp>
#include <simde/types.hpp>

namespace chemcache {

using abs_t     = simde::type::atomic_basis_set;
using shell_t   = simde::type::shell;
using center_t  = simde::type::point;
using shells_t  = std::vector<shell_t>;
using doubles_t = std::vector<double>;
using pure_t    = chemist::ShellType;

abs_t cc_dash_pcvtz_20() {
    // Basis Set name and origin point
    std::string name("cc-pcvtz");
    center_t r0(0.0, 0.0, 0.0);

    auto make_shell = [&r0](auto pure, auto l, const doubles_t& cs,
                            const doubles_t& es) {
        return shell_t(pure, l, cs.begin(), cs.end(), es.begin(), es.end(), r0);
    };

    shells_t shells;
    shells.emplace_back(make_shell(
      pure_t::pure, 0,
      doubles_t{9.3100000000e-06,  7.2390000000e-05,  3.8059000000e-04,
                1.6045300000e-03,  5.8078000000e-03,  1.8595660000e-02,
                5.2877760000e-02,  1.3015149000e-01,  2.5931471000e-01,
                3.6149610000e-01,  2.6411160000e-01,  5.7093980000e-02,
                -1.8220000000e-03, 2.1116400000e-03,  -9.7709000000e-04,
                4.5581000000e-04,  -1.9146000000e-04, 9.1710000000e-05,
                -7.8740000000e-05, 2.2320000000e-05},
      doubles_t{2.4026540000e+06, 3.5978980000e+05, 8.1878090000e+04,
                2.3190890000e+04, 7.5652120000e+03, 2.7307020000e+03,
                1.0646400000e+03, 4.4106050000e+02, 1.9172690000e+02,
                8.6537740000e+01, 3.9899240000e+01, 1.7640650000e+01,
                8.3599900000e+00, 3.9513300000e+00, 1.7134000000e+00,
                8.1086000000e-01, 3.6025000000e-01, 8.1080000000e-02,
                4.4840000000e-02, 2.1430000000e-02}));
    shells.emplace_back(make_shell(
      pure_t::pure, 0,
      doubles_t{-2.7000000000e-06, -2.1020000000e-05, -1.1052000000e-04,
                -4.6666000000e-04, -1.6951300000e-03, -5.4834600000e-03,
                -1.5965970000e-02, -4.1513840000e-02, -9.2863870000e-02,
                -1.6531657000e-01, -1.7664074000e-01, 6.4444220000e-02,
                5.1087962000e-01,  4.9463804000e-01,  8.7500940000e-02,
                -3.5910100000e-03, 2.4922000000e-03,  -7.5825000000e-04,
                6.4587000000e-04,  -1.8174000000e-04},
      doubles_t{2.4026540000e+06, 3.5978980000e+05, 8.1878090000e+04,
                2.3190890000e+04, 7.5652120000e+03, 2.7307020000e+03,
                1.0646400000e+03, 4.4106050000e+02, 1.9172690000e+02,
                8.6537740000e+01, 3.9899240000e+01, 1.7640650000e+01,
                8.3599900000e+00, 3.9513300000e+00, 1.7134000000e+00,
                8.1086000000e-01, 3.6025000000e-01, 8.1080000000e-02,
                4.4840000000e-02, 2.1430000000e-02}));
    shells.emplace_back(make_shell(
      pure_t::pure, 0,
      doubles_t{9.3000000000e-07,  7.2500000000e-06,  3.8110000000e-05,
                1.6101000000e-04,  5.8466000000e-04,  1.8950400000e-03,
                5.5252500000e-03,  1.4470100000e-02,  3.2715810000e-02,
                6.0031900000e-02,  6.7016830000e-02,  -2.5936600000e-02,
                -2.6747467000e-01, -4.2697256000e-01, 6.7964050000e-02,
                7.1020539000e-01,  4.4180057000e-01,  2.1931390000e-02,
                -1.1869240000e-02, 2.6527200000e-03},
      doubles_t{2.4026540000e+06, 3.5978980000e+05, 8.1878090000e+04,
                2.3190890000e+04, 7.5652120000e+03, 2.7307020000e+03,
                1.0646400000e+03, 4.4106050000e+02, 1.9172690000e+02,
                8.6537740000e+01, 3.9899240000e+01, 1.7640650000e+01,
                8.3599900000e+00, 3.9513300000e+00, 1.7134000000e+00,
                8.1086000000e-01, 3.6025000000e-01, 8.1080000000e-02,
                4.4840000000e-02, 2.1430000000e-02}));
    shells.emplace_back(make_shell(pure_t::pure, 0, doubles_t{1.0000000000e+00},
                                   doubles_t{8.1080000000e-02}));
    shells.emplace_back(make_shell(
      pure_t::pure, 0,
      doubles_t{-2.2000000000e-07, -1.7300000000e-06, -9.1000000000e-06,
                -3.8440000000e-05, -1.3965000000e-04, -4.5251000000e-04,
                -1.3203800000e-03, -3.4584100000e-03, -7.8368600000e-03,
                -1.4415170000e-02, -1.6216480000e-02, 6.3442000000e-03,
                6.7406260000e-02,  1.1447396000e-01,  -2.6344770000e-02,
                -2.3369885000e-01, -3.1607538000e-01, 3.3281936000e-01,
                5.6111035000e-01,  2.8081781000e-01},
      doubles_t{2.4026540000e+06, 3.5978980000e+05, 8.1878090000e+04,
                2.3190890000e+04, 7.5652120000e+03, 2.7307020000e+03,
                1.0646400000e+03, 4.4106050000e+02, 1.9172690000e+02,
                8.6537740000e+01, 3.9899240000e+01, 1.7640650000e+01,
                8.3599900000e+00, 3.9513300000e+00, 1.7134000000e+00,
                8.1086000000e-01, 3.6025000000e-01, 8.1080000000e-02,
                4.4840000000e-02, 2.1430000000e-02}));
    shells.emplace_back(make_shell(pure_t::pure, 0, doubles_t{1.0000000000e+00},
                                   doubles_t{2.1430000000e-02}));
    shells.emplace_back(make_shell(pure_t::pure, 0, doubles_t{1.0000000000e+00},
                                   doubles_t{2.0630000000e+00}));
    shells.emplace_back(make_shell(pure_t::pure, 0, doubles_t{1.0000000000e+00},
                                   doubles_t{4.0980000000e-01}));
    shells.emplace_back(make_shell(
      pure_t::pure, 1,
      doubles_t{1.9799000000e-04, 1.7320800000e-03, 9.5337900000e-03,
                3.8390120000e-02, 1.1675881000e-01, 2.5626874000e-01,
                3.7978080000e-01, 3.0829326000e-01, 8.5920900000e-02,
                2.1206700000e-03, 1.2888000000e-03, -4.6835000000e-04,
                1.4728000000e-04, -5.2880000000e-05},
      doubles_t{4.0612890000e+03, 9.6224650000e+02, 3.1216860000e+02,
                1.1871440000e+02, 4.9806700000e+01, 2.2259980000e+01,
                1.0287640000e+01, 4.8611540000e+00, 2.2487730000e+00,
                1.0336620000e+00, 4.6413200000e-01, 1.9875000000e-01,
                6.7390000000e-02, 2.5420000000e-02}));
    shells.emplace_back(make_shell(
      pure_t::pure, 1,
      doubles_t{-6.4550000000e-05, -5.6458000000e-04, -3.1312500000e-03,
                -1.2740860000e-02, -3.9914030000e-02, -9.0504480000e-02,
                -1.4261898000e-01, -1.0980904000e-01, 1.5162490000e-01,
                4.6176411000e-01, 4.3260031000e-01, 1.1127411000e-01,
                2.5287400000e-03, 7.1032000000e-04},
      doubles_t{4.0612890000e+03, 9.6224650000e+02, 3.1216860000e+02,
                1.1871440000e+02, 4.9806700000e+01, 2.2259980000e+01,
                1.0287640000e+01, 4.8611540000e+00, 2.2487730000e+00,
                1.0336620000e+00, 4.6413200000e-01, 1.9875000000e-01,
                6.7390000000e-02, 2.5420000000e-02}));
    shells.emplace_back(make_shell(pure_t::pure, 1, doubles_t{1.0000000000e+00},
                                   doubles_t{1.9875000000e-01}));
    shells.emplace_back(make_shell(
      pure_t::pure, 1,
      doubles_t{1.3360000000e-05, 1.1852000000e-04, 6.4872000000e-04,
                2.6799300000e-03, 8.2851300000e-03, 1.9212350000e-02,
                2.9549840000e-02, 2.4312320000e-02, -4.1112300000e-02,
                -1.0419758000e-01, -1.5036537000e-01, 2.4317290000e-02,
                5.9861164000e-01, 4.8135571000e-01},
      doubles_t{4.0612890000e+03, 9.6224650000e+02, 3.1216860000e+02,
                1.1871440000e+02, 4.9806700000e+01, 2.2259980000e+01,
                1.0287640000e+01, 4.8611540000e+00, 2.2487730000e+00,
                1.0336620000e+00, 4.6413200000e-01, 1.9875000000e-01,
                6.7390000000e-02, 2.5420000000e-02}));
    shells.emplace_back(make_shell(pure_t::pure, 1, doubles_t{1.0000000000e+00},
                                   doubles_t{2.5420000000e-02}));
    shells.emplace_back(make_shell(pure_t::pure, 1, doubles_t{1.0000000000e+00},
                                   doubles_t{2.8806000000e+00}));
    shells.emplace_back(make_shell(pure_t::pure, 1, doubles_t{1.0000000000e+00},
                                   doubles_t{5.3470000000e-01}));
    shells.emplace_back(make_shell(pure_t::pure, 2, doubles_t{1.0000000000e+00},
                                   doubles_t{2.2775000000e+00}));
    shells.emplace_back(make_shell(pure_t::pure, 2, doubles_t{1.0000000000e+00},
                                   doubles_t{1.1270000000e+00}));
    shells.emplace_back(make_shell(pure_t::pure, 2, doubles_t{1.0000000000e+00},
                                   doubles_t{1.4151000000e-01}));
    shells.emplace_back(make_shell(
      pure_t::pure, 2,
      doubles_t{1.5473000000e-02, 7.8874000000e-02, 2.0878000000e-01,
                3.3021300000e-01, 4.3756200000e-01, 3.7479000000e-01},
      doubles_t{1.6946230000e+01, 4.4721200000e+00, 1.4380900000e+00,
                4.6699000000e-01, 1.4151000000e-01, 4.1640000000e-02}));
    shells.emplace_back(make_shell(pure_t::pure, 2, doubles_t{1.0000000000e+00},
                                   doubles_t{4.1640000000e-02}));
    shells.emplace_back(make_shell(pure_t::pure, 3, doubles_t{1.0000000000e+00},
                                   doubles_t{1.3909000000e+00}));
    shells.emplace_back(make_shell(pure_t::pure, 3, doubles_t{1.0000000000e+00},
                                   doubles_t{1.5090000000e-01}));
    return abs_t(name, 20, r0, shells.begin(), shells.end());
} // cc_dash_pcvtz_20

} // namespace chemcache
