name: Build and Deploy Documentation
on:
  push:
    branches:
      - master

jobs:
  Build-Documentation:
    runs-on: ubuntu-latest
    env:
      cmake_version: 3.16.3
      arch: Linux-x86_64
    steps:
      - name: Obtain Source
        uses: actions/checkout@v2
      
      # This implicitly gets Python to get Sphinx
      - name: Get dependencies
        run: .github/workflows/scripts/get_dependencies.sh cmake doxygen sphinx

      - name: Build Python documentation
        run: |
          . venv/bin/activate
          sphinx-apidoc -f -o docs/source/python_api/ reference_data
          deactivate

      - name: Build C++ and overall documentation
        run: .github/workflows/scripts/build_docs.sh chemcache_cxx_api

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.CREATE_PULL_REQUEST_TOKEN }}
          publish_dir: ./docs/build/html