name: Download and Generate Reference Data Code

on:
  # Trigger on push for master branch
  push:
    branches:
      - master

jobs:
  Download-Reference-Data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get source
        uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install venv and dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r reference_data/requirements.txt
      
      - name: Download reference data
        run: .github/workflows/scripts/download_reference_data.sh

      - name: Generate reference data source code
        run: .github/workflows/scripts/generate_reference_data.sh

      # Todo: Commit and push changes to a branch