# Copyright 2023 NWChemEx-Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Merge Workflow

on:
  push:
    branches:
      - master

jobs:
  tag-commit:
    uses: NWChemEx/.github/.github/workflows/tag.yaml@master
    secrets: inherit

  deploy_nwx_docs:
    uses: NWChemEx/.github/.github/workflows/deploy_nwx_docs.yaml@master
    with:
      doc_target: "chemcache_cxx_api"
      generate_module_docs: true
    secrets: inherit

  download-and-generate-reference-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install venv and dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r utils/data_management/requirements.txt
        shell: bash
      - name: Overwrite 'generated_data' with 'master'
        run: |
          git fetch
          git checkout --track origin/generated_data
          git checkout master
          git merge -s ours generated_data -m "Merge branch 'generated_data'" --allow-unrelated-histories
          git checkout generated_data
          git merge master -m "Merge master -> generated_data"
        shell: bash
      - name: Download reference data
        run: .github/workflows/scripts/download_reference_data.sh
      - name: Generate reference data source code
        run: .github/workflows/scripts/generate_reference_data.sh
      - name: Format generated code
        run: find src/ -iname '*.cpp' | xargs clang-format --verbose -i
      - name: Commit and push changes to data branch
        uses: github-actions-x/commit@v2.9
        with:
          push-branch: generated_data
          commit-message: Automatically updated reference data using GitHub Actions